/**
 * MCP server OAuth 2.0 client credentials — stateless HMAC token auth.
 *
 * Environment variables (all required to enable auth):
 *   MCP_CLIENT_ID      — client identifier presented by connectors
 *   MCP_CLIENT_SECRET  — high-entropy secret for credential validation
 *   MCP_TOKEN_SECRET   — separate secret for signing tokens (never transmitted)
 *
 * If MCP_CLIENT_ID is unset, auth is disabled and all requests pass through.
 * This preserves backwards compatibility for local / dev deployments.
 *
 * Legacy support: PULLMD_AUTH_TOKEN still accepted as a static bearer token.
 *
 * Token format:  {client_id}:{expiry_unix}:{hmac_sha256_hex}
 * Validation:    recompute HMAC, timingSafeEqual, check expiry — no DB needed.
 */

import crypto from 'crypto';
import express from 'express';

const TOKEN_TTL = 30 * 24 * 3600; // 30 days in seconds

const CLIENT_ID     = process.env.MCP_CLIENT_ID     || '';
const CLIENT_SECRET = process.env.MCP_CLIENT_SECRET || '';
const TOKEN_SECRET  = process.env.MCP_TOKEN_SECRET  || '';

export const AUTH_ENABLED = Boolean(CLIENT_ID && CLIENT_SECRET && TOKEN_SECRET);

// Paths that never require auth
const EXEMPT_PATHS = new Set([
  '/health',
  '/oauth/token',
]);
const EXEMPT_PREFIX = '/.well-known/';

function isExempt(path) {
  return EXEMPT_PATHS.has(path) || path.startsWith(EXEMPT_PREFIX);
}

function sign(payload) {
  return crypto.createHmac('sha256', TOKEN_SECRET).update(payload).digest('hex');
}

/**
 * Constant-time string comparison. Falls back gracefully when lengths differ
 * (still runs a dummy comparison to avoid early-exit timing leaks).
 */
function timingSafeEqual(a, b) {
  const ba = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ba.length !== bb.length) {
    crypto.timingSafeEqual(ba, ba); // dummy — prevent length-based leak
    return false;
  }
  return crypto.timingSafeEqual(ba, bb);
}

export function generateToken(clientId) {
  const expiry = Math.floor(Date.now() / 1000) + TOKEN_TTL;
  const payload = `${clientId}:${expiry}`;
  return `${payload}:${sign(payload)}`;
}

export function validateToken(token) {
  try {
    const lastColon = token.lastIndexOf(':');
    if (lastColon < 0) return false;
    const payload = token.slice(0, lastColon);
    const sig     = token.slice(lastColon + 1);
    if (!timingSafeEqual(sig, sign(payload))) return false;
    // payload is "{client_id}:{expiry}" — expiry is the last segment
    const expiryStr = payload.slice(payload.lastIndexOf(':') + 1);
    return Math.floor(Date.now() / 1000) <= parseInt(expiryStr, 10);
  } catch {
    return false;
  }
}

export function validateCredentials(clientId, clientSecret) {
  if (!CLIENT_ID || !CLIENT_SECRET) return false;
  return (
    timingSafeEqual(clientId, CLIENT_ID) &&
    timingSafeEqual(clientSecret, CLIENT_SECRET)
  );
}

/**
 * Express middleware — replaces the legacy PULLMD_AUTH_TOKEN bearer check.
 *
 * Priority:
 *  1. Exempt paths pass through unconditionally.
 *  2. If MCP_CLIENT_ID is not set, falls through (dev mode).
 *  3. Accepts signed HMAC tokens (generated by /oauth/token).
 *  4. Also accepts legacy static PULLMD_AUTH_TOKEN for backward compat.
 *  5. Otherwise 401.
 */
export function bearerAuthMiddleware(req, res, next) {
  const path = req.path;

  if (isExempt(path)) {
    return next();
  }

  // Auth disabled in dev mode — MCP_CLIENT_ID not set
  if (!CLIENT_ID) {
    return next();
  }

  const authHeader = req.headers['authorization'] || '';
  if (authHeader.startsWith('Bearer ')) {
    const token = authHeader.slice(7);

    // Accept valid HMAC tokens
    if (AUTH_ENABLED && validateToken(token)) {
      return next();
    }

    // Legacy static token backward compat
    const staticToken = process.env.PULLMD_AUTH_TOKEN;
    if (staticToken && timingSafeEqual(token, staticToken)) {
      return next();
    }
  }

  res.set('WWW-Authenticate', 'Bearer realm="pullmd"');
  return res.status(401).json({
    error: 'unauthorized',
    error_description: 'Valid Bearer token required',
  });
}

// Middleware stack that accepts both JSON and form-encoded bodies
const tokenBodyParsers = [
  express.json({ limit: '16kb' }),
  express.urlencoded({ extended: false, limit: '16kb' }),
];

/**
 * Register OAuth2 discovery and token endpoints on an Express app.
 *
 * GET  /.well-known/oauth-authorization-server  — RFC 8414 metadata
 * GET  /.well-known/oauth-protected-resource    — RFC 9728 metadata
 * POST /oauth/token                             — client_credentials grant
 */
export function registerOAuthRoutes(app) {
  // Authorization server metadata (RFC 8414)
  app.get('/.well-known/oauth-authorization-server', (req, res) => {
    const base = baseUrl(req);
    res.json({
      issuer: base,
      authorization_endpoint: `${base}/authorize`,
      token_endpoint: `${base}/oauth/token`,
      grant_types_supported: ['client_credentials'],
      token_endpoint_auth_methods_supported: ['client_secret_post'],
    });
  });

  // Protected resource metadata (RFC 9728)
  app.get('/.well-known/oauth-protected-resource', (req, res) => {
    const base = baseUrl(req);
    res.json({
      resource: `${base}/mcp`,
      authorization_servers: [base],
      bearer_methods_supported: ['header'],
    });
  });

  // Token endpoint — client_credentials grant only
  app.post('/oauth/token', ...tokenBodyParsers, (req, res) => {
    const { grant_type, client_id, client_secret } = req.body || {};

    if (grant_type !== 'client_credentials') {
      return res.status(400).json({
        error: 'unsupported_grant_type',
        error_description: 'Only client_credentials is supported',
      });
    }

    if (!client_id || !client_secret) {
      return res.status(400).json({
        error: 'invalid_request',
        error_description: 'client_id and client_secret are required',
      });
    }

    if (!validateCredentials(client_id, client_secret)) {
      return res.status(401).json({
        error: 'invalid_client',
        error_description: 'Invalid client credentials',
      });
    }

    const access_token = generateToken(client_id);
    return res.json({
      access_token,
      token_type: 'bearer',
      expires_in: TOKEN_TTL,
    });
  });
}

// Derive base URL from the incoming request (respects reverse-proxy headers)
function baseUrl(req) {
  const proto = req.headers['x-forwarded-proto'] || req.protocol || 'http';
  const host  = req.headers['x-forwarded-host']  || req.headers['host'] || 'localhost';
  return `${proto}://${host}`;
}
